#!/usr/bin/perl -w

# Generates interlinked web pages destudent_courseribing enrollments in this session's COMP courses
# Aidan Barrington UNSW COMP2041 2013 S2

use strict;
use warnings;

my $line;
my %student_course=();
my %course_student=();
my %student_name=();
my %course_name=();

# extract student enrollment data
my $url = "http://cgi.cse.unsw.edu.au/~cs2041/13s2/lab/perl/students/enrollments";
open F, "wget -q -O- $url|" or die "Could not fetch enrollment data";
while ($line = <F>) {
    $line =~ s/.{45}$//g;
    $line =~ s/\s{2,}$//g;
    $line =~ /([A-Z]{4}[0-9]{4})\|([0-9]{7})\|(.*)/;
    my $course_id = $1;
    my $student_id = $2;
    my $student_name = $3;
    push @{$student_course{$student_id}}, $course_id;
    push @{$course_student{$course_id}}, $student_id;
    $student_name{$student_id} = $student_name;
}

# extract course code data
$url = "http://cgi.cse.unsw.edu.au/~cs2041/13s2/lab/perl/students/course_codes";
open F, "wget -q -O- $url|" or die "Could not fetch course data";
while ($line =<F>) {
    $line =~ /([A-Z]{4}[0-9]{4})\s(.*)$/;
    my $course_id = $1;
    my $c_name = $2;
    $course_name{$course_id} = $c_name;
}

# sort the data
my $arrayref;
foreach (keys %student_course) {
    $arrayref = $student_course{$_};
    @$arrayref = sort {$a cmp $b} @$arrayref;
}
foreach (keys %course_student) {
    $arrayref = $course_student{$_};
    @$arrayref = sort {$a <=> $b} @$arrayref;
}

# generate our html pages
my $OUT;
my $index_url = "index.html";

if (-f $index_url) {
    unlink($index_url);
}

open $OUT, '>>', "index.html" or die "Could not generate index.html";

print { $OUT } "
	<!DOCTYPE html>\n<html>\n
  	<head><title>Index</title></head>
  	<body>\n    <h2>Courses</h2>\n    <ul>\n";

foreach (sort keys %course_student) { print { $OUT } "      <li><a href=\"$_.html\">$_ $course_name{$_}</a></li>\n" }

print { $OUT } "
    </ul>\n    <h2>Students</h2>    <ul>\n";

foreach (sort keys %student_course) { 
	print { $OUT } "      <li><a href=\"$_.html\">$_ $student_name{$_}</a></li>\n" }

print { $OUT } "
    </ul>\n    <hr>\n    <small>generated by aidan barrington for lab9 cs2041 s2 unsw 2013 </small>\n  </body>\n</html>";

foreach (keys %student_course) {
    my $file = $_.".html";
    if (-f $file) {
        unlink($file);
    }
    
    open $OUT, '>>', $file or die "Could not create student page";
    print { $OUT } "
	
	<!DOCTYPE html>\n<html>\n
  	<head><title>Courses taken by $_ $student_name{$_}</title></head>\n
  	<body>\n    <h2>Courses taken by $_ $student_name{$_}</h2>\n    <ul>\n";
    
    foreach (@{$student_course{$_}}) {
        print { $OUT } "      <li><a href=\"$_.html\">$_ $course_name{$_}</a></li>\n";
    }
    
    print { $OUT } "
    </ul>\n    <a href=\"index.html\">Back To Index</a>\n
    <hr>\n    <small>generated by aidan barrington for lab9 cs2041 s2 unsw 2013</small>\n  </body>\n</html>";
}

foreach (keys %course_student) {
    my $file = $_.".html";
    if (-f $file) {
        unlink($file);
    }
    open $OUT, '>>', $file or die "Could not create course page";
    print { $OUT } "

	<!DOCTYPE html>\n<html>\n
  	<head><title>Students Enrolled in $_ $course_name{$_}</title></head>\n
  	<body>\n    <h2>Students Enrolled in $_ $course_name{$_}</h2>\n    <ul>\n";
    
    foreach (@{$course_student{$_}}) {
        print { $OUT } "      <li><a href=\"$_.html\">$_ $student_name{$_}</a></li>\n";
    }
    
    print { $OUT } "
    </ul>\n    <a href=\"index.html\">Back To Index</a>\n
    <hr>\n    <small>generated by aidan barrington for lab9 cs2041 s2 unsw 2013</small>\n  </body>\n</html>";
}